[package]
name = "tokio-nats"
version = "0.1.0"
authors = ["Sebastian Zimmer <sebastian.zim@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.0-alpha.6" }
bytes = "0.4.12"
serde_json = "1.0.41"
serde = { version = "1.0.102", features = ["derive"] }
futures-util-preview = "0.3.0-alpha.19"
subslice = "0.2.2"
parking_lot = "0.9.0"
derive_builder = "0.9.0"